kod.13.2.task: stworzenie serwisu zamówień produktów
GrzegorzWoloszyn/Grzegorz-Woloszyn-kodilla-java pull request #21
Opened 2020-04-05 15:39 UTC by GrzegorzWoloszyn

2020-04-06 18:09 UTC, mps4dev requested changes
Drobne uwagi

2020-04-06 18:09 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/Application.java
> +//        RentRequestRetriever rentRequestRetriever = new RentRequestRetriever();
co to za komentarze?

2020-04-06 18:09 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/MailService.java
> +import java.time.LocalDateTime;
do czego powyższy import swing?

2020-04-06 18:09 UTC, mps4dev commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/RentalProcessor.java
> +//package com.kodilla.good.patterns.challenges;
co to?

2020-04-06 20:09 UTC, GrzegorzWoloszyn commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/RentalProcessor.java
> +//package com.kodilla.good.patterns.challenges;
to przykład z submodułu,

2020-04-06 20:09 UTC, GrzegorzWoloszyn commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/MailService.java
> +import java.time.LocalDateTime;
do niczego, usunąłem

2020-04-06 20:09 UTC, GrzegorzWoloszyn commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/Application.java
> +//        RentRequestRetriever rentRequestRetriever = new RentRequestRetriever();
to z przykładów z submodułu

2020-04-07 06:33 UTC, mps4dev approved these changes
Widzę, że lubisz zakomentowany kod.

2020-04-07 21:04 UTC, merged