kod.15.2.task: klonujemy bibliotekę
GrzegorzWoloszyn/Grzegorz-Woloszyn-kodilla-java pull request #31
Opened 2020-05-01 14:17 UTC by GrzegorzWoloszyn

2020-05-01 21:51 UTC, mps4dev requested changes
👎

2020-05-01 21:51 UTC, mps4dev commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +            deepClonedLibrary.getBooks().add(theBook);
add(new Book(theBook.getTitle(), theBook.getAuthor(), title.getPublicationDate()))

2020-05-02 09:19 UTC, GrzegorzWoloszyn commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +            deepClonedLibrary.getBooks().add(theBook);
Będę miał co do tego pytanie, omówimy w środę.

2020-05-02 09:35 UTC, mps4dev approved these changes
👍

2020-05-02 09:39 UTC, merged