kod.6.5: mockujemy forum dyskusyjne
GrzegorzWoloszyn/Grzegorz-Woloszyn-kodilla-java pull request #9
Opened 2020-02-26 22:18 UTC by GrzegorzWoloszyn

Chyba pierwszy udany PR :)

2020-02-27 06:51 UTC, mps4dev requested changes
Prawie dobrze

2020-02-27 06:51 UTC, mps4dev commented on Kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsExecutor.java
> +    Statistics statistics;
Pola jesli juz, to private! Ale tutaj nie potrzebujesz pola, gdyz poniewaz metoda przyjmuje argument typu Statistics.

2020-02-27 06:51 UTC, mps4dev commented on Kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsExecutor.java
> +    private int users, posts, comments;
Rozbij na osobne linijki

2020-02-27 06:51 UTC, mps4dev commented on Kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsExecutor.java
> +    private List<String> user = new ArrayList<>();
Tego nie potrzebujesz jako pola

2020-02-27 06:51 UTC, mps4dev commented on Kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsExecutor.java
> +        users = statistics.username().size();
Tutaj zmienna lokalna userSize

2020-02-27 06:51 UTC, mps4dev commented on Kodilla-testing/src/test/java/com/kodilla/testing/forum/statistics/StatisticsExecutorTestSuite.java
> +    private List<String> users = new ArrayList<>();
Niepotrzebne

2020-02-27 06:51 UTC, mps4dev commented on Kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/Statistics.java
> +    List<String> username();
usernames()

2020-02-27 07:55 UTC, GrzegorzWoloszyn commented on Kodilla-testing/src/test/java/com/kodilla/testing/forum/statistics/StatisticsExecutorTestSuite.java
> +    private List<String> users = new ArrayList<>();
Trochę tak, przeniosłem do testu w którym jest używane.

2020-02-27 10:17 UTC, mps4dev requested changes
A gdzie sa asercje w testach?

2020-02-27 10:17 UTC, mps4dev commented on Kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsExecutor.java
> +            averageCountOfUsersComments = comments / userSize;
Uwaga na dzielenie : int / int = int, czyli musisz scastowac jednego inta na doubla

2020-02-28 12:49 UTC, mps4dev approved these changes
👍

2020-02-28 20:11 UTC, merged